# Sphinx configuration for the datalad-fuse documentation.
#
# See https://www.sphinx-doc.org/en/master/usage/configuration.html

import datetime
from os.path import abspath, dirname, exists
from os.path import join as opj
import subprocess
import sys

import datalad_fuse
import datalad_fuse.fsspec

docs_source = dirname(abspath(__file__))
repo_root = dirname(dirname(docs_source))

# Generate the RST man pages for the commands (docs/source/generated/man/)
# with the helper from _datalad_buildsupport.
setup_py = opj(repo_root, "setup.py")
if exists(setup_py):
    subprocess.run(
        [
            sys.executable,
            setup_py,
            "build_manpage",
            "--cmdsuite",
            "datalad_fuse:command_suite",
            "--manpath",
            opj(repo_root, "build", "man"),
            "--rstpath",
            opj(docs_source, "generated", "man"),
        ],
        cwd=repo_root,
        check=True,
    )

# Methods decorated with methodtools.lru_cache are hidden behind a descriptor
# that autodoc does not recognize as a method.  For the documentation only,
# replace them with the functions they wrap, so that they are documented.
for _cls in (datalad_fuse.fsspec.DatasetAdapter, datalad_fuse.fsspec.FsspecAdapter):
    for _name, _attr in list(vars(_cls).items()):
        if type(_attr).__module__.startswith("wirerope") and hasattr(
            _attr, "__wrapped__"
        ):
            setattr(_cls, _name, _attr.__wrapped__)

# -- General configuration ------------------------------------------------

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.intersphinx",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx_copybutton",
    "myst_parser",
]

project = "datalad-fuse"
copyright = "2021-{}, DataLad team".format(datetime.datetime.now().year)
author = "DataLad team"

version = datalad_fuse.__version__
release = version

language = "en"
master_doc = "index"
source_suffix = {".rst": "restructuredtext", ".md": "markdown"}
templates_path = ["_templates"]
exclude_patterns = []

# `single backticks` refer to Python objects
default_role = "py:obj"

pygments_style = "sphinx"

# for the module reference
autosummary_generate = True
autodoc_member_order = "bysource"
autodoc_typehints = "description"
autodoc_default_options = {"members": True, "show-inheritance": True}
# fusepy needs libfuse at import time; mock it if libfuse is not installed
try:
    import fuse  # noqa: F401
except (ImportError, OSError):
    autodoc_mock_imports = ["fuse"]

napoleon_google_docstring = False
napoleon_numpy_docstring = True

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "datalad": ("https://docs.datalad.org/en/stable", None),
    "fsspec": ("https://filesystem-spec.readthedocs.io/en/latest", None),
}

# Make the "$ " prompt and output in console examples not copyable
copybutton_exclude = ".linenos, .gp, .go"

myst_heading_anchors = 3
# CHANGELOG.md is generated by `auto`: its headings jump from H1 to H4, and
# PR titles such as "[gh-actions](deps): ..." look like links to documents
suppress_warnings = ["myst.header", "myst.xref_missing"]

# -- Options for HTML output ----------------------------------------------

html_theme = "sphinx_rtd_theme"
html_logo = "_static/datalad_logo.png"
html_static_path = ["_static"]
html_show_sourcelink = False
html_context = {
    "display_github": True,
    "github_user": "datalad",
    "github_repo": "datalad-fuse",
    "github_version": "master",
    "conf_py_path": "/docs/source/",
}
