name: FUSE Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 7 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up system
        shell: bash
        run: |
          bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
          # enable repo for devel git-annex, if needed
          #sudo sed -e 's|\(deb.*data\)|#\1|' -e 's|/debian |/debian-devel |' /etc/apt/sources.list.d/neurodebian.sources.list | sudo tee /etc/apt/sources.list.d/neurodebian-devel.sources.list
          sudo apt-get update -qq
          sudo apt-get install eatmydata
          sudo eatmydata apt-get install -y fuse git-annex-standalone

      - uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install coverage datalad tox

      - name: Run tests
        run: |
          # give detailed info on actual test setup
          datalad wtf
          tox -e py3 -- --libfuse
          coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
          name: libfuse
